name: TestPlugin
main: kr.starly.testplugin.TestPlugin
author: Starly Team
website: http://starly.kr/

description: TestPlugin

depend: [ StarlyCore ]

version: 1.0
api-version: 1.13

commands:
  test: